spring.application.name=backend

# ----------------------------------------
# 1. DATABASE CONNECTION (NEON)
# ----------------------------------------
spring.datasource.url=jdbc:postgresql://ep-winter-sky-alco8d5e-pooler.c-3.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_uJVR9i2WfdIG&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=***

# Tell Java which database dialect to speak
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ----------------------------------------
# 2. HIBERNATE SETTINGS (CRITICAL)
# ----------------------------------------
# Since we already built our massive SQL tables manually, 
# we set this to 'validate' so Java NEVER tries to overwrite or delete them.
spring.jpa.hibernate.ddl-auto=update

# Show the SQL queries in the terminal so we can debug later
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Stripe Test Key
stripe.secret.key=***

# Setări Email (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bcineva9@gmail.com
spring.mail.password=***
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Cheia secreta pentru Chatbot AI (Google Gemini)
ai.api.key=***